const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const ctx = {window: {__BASE_PATH__: '/preview'}};
vm.runInNewContext(fs.readFileSync(__dirname + '/../assets/data/apartments.js', 'utf8'), ctx);
vm.runInNewContext(fs.readFileSync(__dirname + '/residence-media.js', 'utf8'), ctx);
const api = ctx.window.AF_RESIDENCE_MEDIA;
assert.deepEqual(Array.from(ctx.window.AF_APARTMENTS.filter(api.hasMedia), a => a.apartmentNumber), ['205','305','405','505']);
assert.equal(api.hasMedia({apartmentNumber:'605',planImageUrl:'/assets/img/plans/40,5.png'}),false);
assert.equal(api.hasMedia({apartmentNumber:'205',planImageUrl:'/another-plan.png'}),false);
const apt=ctx.window.AF_APARTMENTS.find(a=>a.apartmentNumber==='305');
const html=api.render(apt,s=>s);
assert.equal((html.match(/role="tab"/g)||[]).length,3);
assert.ok(html.includes('Вариант ремонта'));
assert.ok(html.includes('/preview/assets/residences/40-5/model.html'));
assert.ok(!html.includes('<iframe'), 'Model must load on demand');
assert.ok(!html.includes('imagegen') && !html.includes('Промпты'));
assert.equal(api.images.length,5);
assert.ok(api.asset('02-living.png').startsWith('/preview/assets/'));
console.log('PASS: only four matching residences, lazy model, gallery and subpath support');
